before_install:
 - sudo add-apt-repository ppa:trevorbernard/zeromq -y
 - sudo apt-get update -y
 - sudo apt-get install libzmq-dev libpgm-dev
 - sudo make install
 - wget https://github.com/zeromq/jzmq-api/raw/master/debs/jzmq_2.1.2-1_amd64.deb
 - sudo dpkg -i jzmq_2.1.2-1_amd64.deb
language: clojure
lein: lein2
script: lein2 all test
jdk:
  - openjdk7
  - openjdk6
